# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uniclip < Formula
  desc "Cross-platform shared clipboard"
  homepage "https://github.com/meliksah/uniclip"
  version "2.3.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/meliksah/uniclip/releases/download/v2.3.6/uniclip_2.3.6_Darwin_arm64.tar.gz"
      sha256 "df294b6006f718b104bac97b24f9000848f4c776e8440647b0e37643913ac540"

      def install
        bin.install "uniclip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/meliksah/uniclip/releases/download/v2.3.6/uniclip_2.3.6_Darwin_x86_64.tar.gz"
      sha256 "7fb29abf8f91b32c11e88132060ee382018e4f35f01433f7ade45e0d5d99f7fb"

      def install
        bin.install "uniclip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meliksah/uniclip/releases/download/v2.3.6/uniclip_2.3.6_Linux_arm64.tar.gz"
      sha256 "1ee85f0b3b888ea932b544a2d8dc1b7cc7292f353e76557bd3e7778a8bbb2c7f"

      def install
        bin.install "uniclip"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/meliksah/uniclip/releases/download/v2.3.6/uniclip_2.3.6_Linux_x86_64.tar.gz"
      sha256 "b4551d9f20750392b1b32e6a58af4e8ed998e8de906d0d9ed34071d47f58f711"

      def install
        bin.install "uniclip"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/meliksah/uniclip/releases/download/v2.3.6/uniclip_2.3.6_Linux_armv6.tar.gz"
      sha256 "279145ea4b3fec16619c5a484ed91d5980d78e300242790b82eecb6fe4fb8cd5"

      def install
        bin.install "uniclip"
      end
    end
  end
end
